version: "3.8"
services:
  aws-cli:
    build:
      context: ./docker/aws-cli
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./aws-cli/workdir
        target: /home/aws-iam/workdir
      - type: bind
        source: ./aws-cli/.ssh
        target: /home/aws-iam/.ssh
    user: aws-iam
    env_file:
      - ./.env
    tty: true
    stdin_open: true
